# Generated by Django 2.2.2 on 2019-08-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset_mgmt', '0001_initial'),
        ('bcbsnc_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcatalog',
            name='analytic_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyticarea_asset', to='bcbsnc_mgmt.AnalyticFocus', verbose_name='Analytic Focus Area'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='analytic_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytictype_asset', to='bcbsnc_mgmt.AnalyticType', verbose_name='Analytic Type'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='asset_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='develop_asset', to='bcbsnc_mgmt.UserProfile', verbose_name='Developer'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='asset_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcbsnc_mgmt.TableauServer', verbose_name='Server'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='asset_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_assets', to='bcbsnc_mgmt.TableauSite', verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='asset_studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_assets', to='bcbsnc_mgmt.AlteryxStudio', verbose_name='Studio'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bcbsnc_mgmt.AssetType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='business_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bparea_asset', to='bcbsnc_mgmt.BusinessArea', verbose_name='Business Process Area'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='business_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_assets', to='bcbsnc_mgmt.UserProfile', verbose_name='Business Owner'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='capability_business',
            field=models.ManyToManyField(blank=True, related_name='capability_asset', to='bcbsnc_mgmt.BusinessCapability', verbose_name='Capability'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='data_source',
            field=models.ManyToManyField(blank=True, related_name='source_asset', to='bcbsnc_mgmt.DataSource', verbose_name='Data Source'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='product_business',
            field=models.ManyToManyField(blank=True, related_name='group_asset', to='bcbsnc_mgmt.LineOfBusiness', verbose_name='Line of Business'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='provider_focus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_asset', to='bcbsnc_mgmt.ProviderFocus', verbose_name='Provider Program'),
        ),
        migrations.AddField(
            model_name='assetcatalog',
            name='utilization_category',
            field=models.ManyToManyField(blank=True, related_name='utilization_asset', to='bcbsnc_mgmt.UtilizationCategory', verbose_name='Utilization Category'),
        ),
    ]
